name: market_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: 2.2.3
  market_client:
    git:
      url: https://github.com/SlayerOrnstein/market_client.git
      ref: v4.0.2
  user_settings:
    path: ../user_settings
  warframestat_client:
    git:
      url: https://github.com/SlayerOrnstein/warframestat_client.git
      ref: v1.8.0

dependency_overrides:
  uuid: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
