name: market_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: 2.2.3
  market_client:
    git:
      url: https://github.com/SlayerOrnstein/market_client.git
      ref: 2417521468a17f0dc3cf7ed5b2d4265bff15efaf
  user_settings:
    path: ../user_settings
  warframestat_client:
    git:
      url: https://github.com/SlayerOrnstein/warframestat_client.git
      ref: v1.5.21

dependency_overrides:
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
