import 'dart:io';

import 'package:navis/resources/resources.dart';
import 'package:test/test.dart';

void main() {
  test('mod_frames assets test', () {
    expect(true, File(ModFrames.ashenHeader).existsSync());
    expect(true, File(ModFrames.augurHeader).existsSync());
    expect(true, File(ModFrames.bonebladeHeader).existsSync());
    expect(true, File(ModFrames.bronzeBackground).existsSync());
    expect(true, File(ModFrames.bronzeCornerLights).existsSync());
    expect(true, File(ModFrames.bronzeFrameBottom).existsSync());
    expect(true, File(ModFrames.bronzeFrameTop).existsSync());
    expect(true, File(ModFrames.bronzeLowerTab).existsSync());
    expect(true, File(ModFrames.bronzeSideLight).existsSync());
    expect(true, File(ModFrames.bronzeTopRightBacker).existsSync());
    expect(true, File(ModFrames.femurHeader).existsSync());
    expect(true, File(ModFrames.gladiatorHeader).existsSync());
    expect(true, File(ModFrames.goldBackground).existsSync());
    expect(true, File(ModFrames.goldCornerLights).existsSync());
    expect(true, File(ModFrames.goldFrameBottom).existsSync());
    expect(true, File(ModFrames.goldFrameTop).existsSync());
    expect(true, File(ModFrames.goldLowerTab).existsSync());
    expect(true, File(ModFrames.goldSideLight).existsSync());
    expect(true, File(ModFrames.goldTopRightBacker).existsSync());
    expect(true, File(ModFrames.hawkHeader).existsSync());
    expect(true, File(ModFrames.hunterHeader).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowChaos).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowDecay).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowEmpty).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowForm).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowLight).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowOrder).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowSlash).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowTime).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowTruth).existsSync());
    expect(true, File(ModFrames.immortalRuneGlowVoid).existsSync());
    expect(true, File(ModFrames.legendaryBackground).existsSync());
    expect(true, File(ModFrames.legendaryCornerLights).existsSync());
    expect(true, File(ModFrames.legendaryFrameBottom).existsSync());
    expect(true, File(ModFrames.legendaryFrameTop).existsSync());
    expect(true, File(ModFrames.legendaryLowerTab).existsSync());
    expect(true, File(ModFrames.legendarySideLight).existsSync());
    expect(true, File(ModFrames.legendaryTopRightBacker).existsSync());
    expect(true, File(ModFrames.mechaHeader).existsSync());
    expect(true, File(ModFrames.raptorHeader).existsSync());
    expect(true, File(ModFrames.requiemModCharge).existsSync());
    expect(true, File(ModFrames.requiemModDamage).existsSync());
    expect(true, File(ModFrames.requiemModFrame).existsSync());
    expect(true, File(ModFrames.silverBackground).existsSync());
    expect(true, File(ModFrames.silverCornerLights).existsSync());
    expect(true, File(ModFrames.silverFrameBottom).existsSync());
    expect(true, File(ModFrames.silverFrameTop).existsSync());
    expect(true, File(ModFrames.silverLowerTab).existsSync());
    expect(true, File(ModFrames.silverSideLight).existsSync());
    expect(true, File(ModFrames.silverTopRightBacker).existsSync());
    expect(true, File(ModFrames.spiderHeader).existsSync());
    expect(true, File(ModFrames.strainHeader).existsSync());
    expect(true, File(ModFrames.synthHeader).existsSync());
    expect(true, File(ModFrames.tekHeader).existsSync());
    expect(true, File(ModFrames.umbraHeader).existsSync());
    expect(true, File(ModFrames.vigilanteHeader).existsSync());
  });
}
