version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directories:
      - "/"
      - "/packages/**"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "00:00"
    groups:
      firebase:
        patterns:
          - firebase_*

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directories:
      - "/android"
      - "/ios"
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "00:00"
