version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/navis_ui"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/notification_repository"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/worldstate_repository"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/inventoria"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/http_client"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/fish_repository"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/android"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/ios"
    target-branch: "master"
    schedule:
      interval: "daily"
