version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/android"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/ios"
    target-branch: "master"
    schedule:
      interval: "daily"
