plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: perf
          release: patch
  - "@semantic-release/release-notes-generator"
branches:
  - name: master
    channel: alpha
    prerelease: alpha
  - name: beta
    channel: beta
    prerelease: true
  - name: stable
