plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: perf
          release: patch
  - - "@semantic-release/release-notes-generator"
    - presets: conventionalcommits
branches:
  - name: master
  - name: beta
    prerelease: true
