plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: perf
          release: patch
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - prepareCmd: "./deploy.sh ${nextRelease.version}"
  - - "@semantic-release/git"
    - assets: ["pubspec.yaml"]
      message: "chore(release): ${nextRelease.version}"
branches:
  - master
