include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/generated/l10n.dart
    - lib/generated/intl/messages_*.dart
    - lib/src/**/*g.dart
    - lib/src/models/**/*.g.dart
    - lib/firebase_options.dart

linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    weight-of-class: 0.33
  metrics-exclude:
    - test/**
  rules:
    - avoid-late-keyword
    - avoid-global-state
    - avoid-non-null-assertion
    - avoid-non-null-assertion
    - avoid-unused-parameters
    - double-literal-format
    - format-comment
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-arguments
    - no-equal-then-else
    - no-magic-number
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-moving-to-variable
    - prefer-trailing-comma

    # Flutter Specific
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-use-expanded-as-spacer
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true

