include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - lib/generated/l10n.dart
    - lib/generated/intl/messages_*.dart
    - lib/src/**/*g.dart
    - lib/src/models/**/*.g.dart
    - lib/firebase_options.dart

linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
