include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/firebase_options.dart
    - lib/router/routes.g.dart
    - packages/navis_ui/lib/src/icons/warframe_symbols.dart
    - packages/warframestat_repository/lib/hive_registrar.g.dart
    - packages/warframestat_repository/lib/src/cache_client.g.dart

linter:
  rules:
    public_member_api_docs: false
    library_private_types_in_public_api: false
    always_put_required_named_parameters_first: false
