include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

analyzer:
  exclude:
    - lib/firebase_options.dart
    - lib/router/routes.g.dart
    - packages/navis_ui/lib/src/icons/warframe_symbols.dart
    - packages/codex/lib/src/schema/*.g.dart
    - packages/inventoria/lib/src/*.g.dart
    - packages/inventoria/test/drift/inventoria/**

linter:
  rules:
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
    lines_longer_than_80_chars: false
    discarded_futures: false
