/// Flutter icons AppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData sortie = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData standing = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData voidfissure = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData archwing = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData nightmare = IconData(0xe804, fontFamily: _kFontFam);
}
