/// Flutter icons FactionIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FactionIcons
///      fonts:
///       - asset: fonts/FactionIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FactionIcons {
  FactionIcons._();

  static const _kFontFam = 'FactionIcons';

  static const IconData corrupted = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData grineer = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData infested = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData corpus = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData sentient = IconData(0xe809, fontFamily: _kFontFam);
}
