/// Flutter icons PlatformIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PlatformIcons
///      fonts:
///       - asset: fonts/PlatformIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PlatformIcons {
  PlatformIcons._();

  static const _kFontFam = 'PlatformIcons';

  static const IconData steam = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData xbox = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData nintendoswitch =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData playstation = IconData(0xe80c, fontFamily: _kFontFam);
}
