/// Flutter icons RelicIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RelicIcons
///      fonts:
///       - asset: fonts/RelicIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RelicIcons {
  RelicIcons._();

  static const _kFontFam = 'RelicIcons';

  static const IconData lith = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData meso = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData neo = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData axi = IconData(0xe810, fontFamily: _kFontFam);
}
