/// Flutter icons SyndicateIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SyndicateIcons
///      fonts:
///       - asset: fonts/SyndicateIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SyndicateIcons {
  SyndicateIcons._();

  static const _kFontFam = 'SyndicateIcons';

  static const IconData nightwavesyndicate =
      IconData(0xe811, fontFamily: _kFontFam);
  static const IconData ostronsigil = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData simaris = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData solarisunited = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData hexis = IconData(0xe815, fontFamily: _kFontFam);
}
