/// Flutter icons SyndicateGlyphs
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SyndicateGlyphs
///      fonts:
///       - asset: fonts/SyndicateGlyphs.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SyndicateGlyphs {
  SyndicateGlyphs._();

  static const _kFontFam = 'SyndicateGlyphs';

  static const IconData ostron = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData solaris = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData simaris = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData hexis = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData nightwave = IconData(0xe804, fontFamily: _kFontFam);
}
