name: fish_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

resolution: workspace

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0
  mocktail: ^1.0.4

flutter:
  generate: true
  assets:
    - assets/fish/

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
