name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: how-do-it
    attributes:
      label: How to Reproduce
      description: Steps to reproduce the behavior
      placeholder: So this is how it happened
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: This is what I expected
    validations:
      required: true  
  - type: dropdown
    id: platforms
    attributes:
      label: What platform are you using Navis on
      options:
        - Android
        - iOS
    validations:
      required: true
  - type: trextarea
    id: platform-version
    attributes:
      label: Platform Version
      description: The version of the platform, i.e. Android 11, iOS 14, etc.
    validations:
      required: true            
  - type: textarea
    id: version
    attributes:
      label: Cephalon Navis version
      description: What version of Navis are you running?
      placeholder: "Find the version in Settings -> About Cephalon Navis"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Anything else that you think we may need to know    
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true