name: Feature request
description: Suggest an idea for this project
title: '[Feature] <title>'
labels: enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: i.e. I'm always frustrated when [...]
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you would like.
      description: A clear and concise description of the proposed feature.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or mockups about the feature request here.
