name: user_settings
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  matomo_tracker: ^3.1.0
  notification_repository:
    path: ../notification_repository
  warframestat_client:
    git:
      url: https://github.com/SlayerOrnstein/warframestat_client.git
      ref: v1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
