name: http_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

resolution: workspace

dependencies:
  cronet_http: ^1.6.0
  crypto: ^3.0.6
  # cupertino_http: ^2.3.0
  flutter:
    sdk: flutter
  flutter_ua: ^1.0.1
  hive_ce: ^2.15.1
  http: ^1.5.0
  meta: 1.16.0
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  hive_ce_generator: ">=1.0.0 <2.0.0"
  mocktail: ^1.0.4
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
