name: worldstate_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  crypto: ^3.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  hive: ^2.2.3
  warframestat_client:
    git:
      url: https://github.com/SlayerOrnstein/warframestat_client.git
      ref: v1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
