name: worldstate_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  hive: ^2.2.3
  http: ^1.2.0
  sentry_hive: ^7.18.0
  warframestat_client: ^3.6.8

dependency_overrides: 
  web: 0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  mocktail: ^1.0.0
  path: ^1.8.3
  very_good_analysis: ^5.1.0
