name: worldstate_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  arbi_api:
    path: ../arbi_api
  cache:
    path: ../cache
  crypto: ^3.0.7
  warframe_api:
    path: ../warframe_api
  warframe_common:
    path: ../warframe_common
  warframe_drop_repository:
    path: ../warframe_drop_repository

dev_dependencies:
  very_good_analysis: ^10.3.0
