name: worldstate_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  hive: ^2.2.3
  user_settings:
    path: ../user_settings
  wfcd_client:
    git:
      url: https://github.com/SlayerOrnstein/wfcd_client.git
      ref: v3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
