import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:path/path.dart' as path;
import 'package:test/test.dart';
import 'package:wfcd_client/clients.dart';
import 'package:worldstate_api_model/entities.dart';

void main() {
  const _baseUrl = 'https://drops.warframestat.us/data/info.json';
  final directory = Directory.systemTemp;

  File dropTable;
  DropTableClient client;
  DateTime currentTimestamp;

  setUpAll(() async {
    dropTable = File(path.join(directory.path, 'drop_table.json'));
    client = DropTableClient(directory.path);

    final response =
        json.decode((await http.get(_baseUrl)).body) as Map<String, dynamic>;

    currentTimestamp =
        DateTime.fromMillisecondsSinceEpoch(response['timestamp'] as int);
  });

  tearDownAll(() {
    dropTable.delete();
  });

  test('Download drop table', () async {
    await client.downloadDropTable();

    expect(dropTable.existsSync(), true);
  });

  test('Serialize drop table json', () async {
    final dropTable = await client.getDropTable();

    expect(dropTable, const TypeMatcher<List<SlimDrop>>());
  });

  test('Make we get the proper timestamp generated by WFCD', () async {
    final timestamp = await client.dropsTimestamp();

    expect(timestamp, currentTimestamp);
  });
}
