# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
setup_travis
update_fastlane

default_platform(:ios)

before_all do |lane|
  tags = git_tags(limit: 2)
  analyze_commits(match: tags[1])

  changelog = conventional_changelog(
    format: 'plain',
    display_title: false,
    display_links: false,
    order: ["feat", "fix", "perf"],
  )

  File.open("metadata/en-US/release_notes.txt", 'w') {|f| f.write(changelog)}
end

platform :ios do
  desc "Push to App Store"
  lane :production do
    begin
      deliver(
        submit_for_review: true,
        automatic_release: true,
        force: true, # Skip HTMl report verification
        skip_metadata: true,
        skip_screenshots: true,
        ipa: '../build/ios/ipa/Navis.ipa',
        metadata_path: "./metadata"
      )
    rescue => exception
      raise exception unless exception.message.include?('The provided entity includes a relationship with an invalid value')
      puts 'Current version already present. Omitting this upload'
    end
  end

  desc "Push build to TestFlight"
  lane :beta do
    begin
      upload_to_testflight(
        distribute_external: true,
        groups: ["Zariman Ten Zero"],
        changelog: generate_changelog,
        ipa: '../build/ios/ipa/Navis.ipa'
      )
    rescue => exception
      raise exception unless exception.message.include?('The provided entity includes a relationship with an invalid value')
      puts 'Current version already present. Omitting this upload'
    end
  end
end