# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
setup_travis
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push to App Store"
  lane :production do
    begin
      tags = git_tags(limit: 2)
      analyze_commits(match: tags[1])
      changelog = conventional_changelog(format: 'plain', display_title: false, display_links: false, order: ['feat', 'fix', 'perf'])

      File.open('metadata/en-US/release_notes.txt', 'w') {|f| f.write(changelog)}

      deliver(
        submit_for_review: true,
        automatic_release: true,
        reject_if_possible: true,
        force: true, # Skip HTMl report verification
        skip_screenshots: true,
        ipa: '../build/ios/ipa/Navis.ipa',
        submission_information: {
          add_id_info_limits_tracking: true,
          add_id_info_serves_ads: false,
          add_id_info_tracks_action: true,
          add_id_info_tracks_install: true,
          add_id_info_uses_idfa: true,
          content_rights_has_rights: true,
          content_rights_contains_third_party_content: true,
          export_compliance_platform: 'ios',
          export_compliance_compliance_required: false,
          export_compliance_encryption_updated: false,
          export_compliance_app_type: nil,
          export_compliance_uses_encryption: false,
          export_compliance_is_exempt: false,
          export_compliance_contains_third_party_cryptography: false,
          export_compliance_contains_proprietary_cryptography: false,
          export_compliance_available_on_french_store: true
        }
      )
    rescue => exception
      raise exception unless exception.message.include?('The provided entity includes a relationship with an invalid value')
      puts 'Current version already present. Omitting this upload'
    end
  end

  desc "Push build to TestFlight"
  lane :beta do
    begin
      tags = git_tags(limit: 2)
      analyze_commits(match: tags[1])
  
      changelog = conventional_changelog(format: 'plain', display_title: false, display_links: false, order: ['feat', 'fix', 'perf'])

      upload_to_testflight(
        distribute_external: true,
        groups: ["Zariman Ten Zero"],
        changelog: changelog,
        ipa: '../build/ios/ipa/Navis.ipa'
      )
    rescue => exception
      raise exception unless exception.message.include?('The provided entity includes a relationship with an invalid value')
      puts 'Current version already present. Omitting this upload'
    end
  end
end