# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
setup_travis
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    begin
      sync_code_signing(type: "appstore")
      get_push_certificate

      # This will build again, becasue currently flutter builds an .app
      # instead of a .ipa which isn't good for deployment to App Store
      build_ios_app(scheme: "Runner", export_method: "app-store")
      upload_to_testflight(skip_waiting_for_build_processing: true)
    rescue => exception
      raise exception unless exception.message.include?('ITMS-90189')
      puts 'Current version already present. Omitting this upload'
    end
  end
end
