/// Flutter icons GenesisAssets
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GenesisAssets
///      fonts:
///       - asset: fonts/GenesisAssets.ttf
///
///
///
import 'package:flutter/widgets.dart';

class GenesisAssets {
  GenesisAssets._();

  static const _kFontFam = 'GenesisAssets';
  static const String? _kFontPkg = null;

  static const IconData sentient =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData simaris =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData solaris =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData standing =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData weekly =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData narmer =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData arbitrations =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData archwing =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData axi =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData baro =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData corpus =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData corrupted =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData daily =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData elite =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData entrati =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData grineer =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData hexis =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData infested =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData kuva =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData kuvaflood =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData lith =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData lotus =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData meso =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData neo =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData nightmare =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData nightwave =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData ostron =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData requiem =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const IconData wfcdLogo =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
