// Place fonts/Warframe-symbols.ttf in your fonts/ directory and
// add the following to your pubspec.yaml
// flutter:
//   fonts:
//    - family: Warframe-symbols
//      fonts:
//       - asset: fonts/Warframe-symbols.ttf
import 'package:flutter/widgets.dart';

class WarframeSymbols {
  WarframeSymbols._();

  static const String _fontFamily = 'Warframe-symbols';
  static const String _fontPackage = 'navis_ui';

  static const IconData arbitrations =
      IconData(0xf101, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData archwing =
      IconData(0xf102, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData damage_impact =
      IconData(0xf103, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData damage_puncture =
      IconData(0xf104, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData damage_slash =
      IconData(0xf105, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData entrati =
      IconData(0xf106, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData factions_corpus =
      IconData(0xf107, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData factions_corrupted =
      IconData(0xf108, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData factions_grineer =
      IconData(0xf109, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData factions_infested =
      IconData(0xf10a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData factions_murmur =
      IconData(0xf10b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData factions_narmer =
      IconData(0xf10c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData factions_narmer2 =
      IconData(0xf10d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData factions_sentient =
      IconData(0xf10e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fissures_axi =
      IconData(0xf10f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fissures_lith =
      IconData(0xf110, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fissures_meso =
      IconData(0xf111, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fissures_neo =
      IconData(0xf112, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fissures_requiem =
      IconData(0xf113, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData hexis =
      IconData(0xf114, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData kuva_kuva =
      IconData(0xf115, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData kuva_kuvaflood =
      IconData(0xf116, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData loading =
      IconData(0xf117, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_All =
      IconData(0xf118, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Amp =
      IconData(0xf119, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Arcane =
      IconData(0xf11a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Archwing =
      IconData(0xf11b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ArchwingColour =
      IconData(0xf11c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ArchwingEmblem =
      IconData(0xf11d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ArchwingPrimary =
      IconData(0xf11e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ArchwingSecondary =
      IconData(0xf11f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Armor =
      IconData(0xf120, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Augment =
      IconData(0xf121, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Aura =
      IconData(0xf122, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Avionics =
      IconData(0xf123, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_AvionicsDefensive =
      IconData(0xf124, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_AvionicsOffensive =
      IconData(0xf125, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_AvionicsSuper =
      IconData(0xf126, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_AvionicsTactical =
      IconData(0xf127, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Barracks =
      IconData(0xf128, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Bile =
      IconData(0xf129, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Biotics =
      IconData(0xf12a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Blueprint =
      IconData(0xf12b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Build =
      IconData(0xf12c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Calx =
      IconData(0xf12d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Capacity =
      IconData(0xf12e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Cephalon =
      IconData(0xf12f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CetusElder =
      IconData(0xf130, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ChangeSkins =
      IconData(0xf131, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ClanObstacleCourse =
      IconData(0xf132, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Command =
      IconData(0xf133, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Connector =
      IconData(0xf134, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Corpus =
      IconData(0xf135, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingAmpBrace =
      IconData(0xf136, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingAmpPrism =
      IconData(0xf137, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingAmpScaffold =
      IconData(0xf138, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingHoundBody =
      IconData(0xf139, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingHoundHead =
      IconData(0xf13a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingHoundLegs =
      IconData(0xf13b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingHoundTail =
      IconData(0xf13c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingKDriveBoard =
      IconData(0xf13d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingKDriveJet =
      IconData(0xf13e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingKDriveNose =
      IconData(0xf13f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingKDriveReactor =
      IconData(0xf140, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingKitgunChamber =
      IconData(0xf141, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingKitgunGrip =
      IconData(0xf142, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingKitgunLoader =
      IconData(0xf143, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingKitgunPrimaryGrip =
      IconData(0xf144, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingMoaBrackets =
      IconData(0xf145, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingMoaCore =
      IconData(0xf146, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingMoaGyro =
      IconData(0xf147, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_CraftingMoaModel =
      IconData(0xf148, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Displays =
      IconData(0xf149, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Drone =
      IconData(0xf14a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Duplicate =
      IconData(0xf14b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Emotes =
      IconData(0xf14c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Energy =
      IconData(0xf14d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Engineering =
      IconData(0xf14e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Entrati =
      IconData(0xf14f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Equip =
      IconData(0xf150, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Exilus =
      IconData(0xf151, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Favorite =
      IconData(0xf152, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_FishLarge =
      IconData(0xf153, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_FishMedium =
      IconData(0xf154, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_FishSmall =
      IconData(0xf155, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Fusion =
      IconData(0xf156, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Fx =
      IconData(0xf157, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Gara =
      IconData(0xf158, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Garden =
      IconData(0xf159, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Gear =
      IconData(0xf15a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_GearWheel =
      IconData(0xf15b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_GeneticImprint =
      IconData(0xf15c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Ghouls =
      IconData(0xf15d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Gift =
      IconData(0xf15e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Glyph =
      IconData(0xf15f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Grineer =
      IconData(0xf160, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Grip =
      IconData(0xf161, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Gunnery =
      IconData(0xf162, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Hall =
      IconData(0xf163, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Incomplete =
      IconData(0xf164, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_IndividualObstacleCourse =
      IconData(0xf165, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Infested =
      IconData(0xf166, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Kavat =
      IconData(0xf167, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Keys =
      IconData(0xf168, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Kubrow =
      IconData(0xf169, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_KuvaLichActive =
      IconData(0xf16a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_KuvaLichConverted =
      IconData(0xf16b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_KuvaLichTraded =
      IconData(0xf16c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_KuvaLichVanquished =
      IconData(0xf16d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Lab =
      IconData(0xf16e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_LichCategory =
      IconData(0xf16f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_LimitedTime =
      IconData(0xf170, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Link =
      IconData(0xf171, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_LotusEmblem =
      IconData(0xf172, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ManufacturerLavan =
      IconData(0xf173, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ManufacturerSigma =
      IconData(0xf174, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ManufacturerVidar =
      IconData(0xf175, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ManufacturerZekti =
      IconData(0xf176, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Materials =
      IconData(0xf177, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_MaterialsOff =
      IconData(0xf178, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Mech =
      IconData(0xf179, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_MechBoard =
      IconData(0xf17a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Melee =
      IconData(0xf17b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Misc =
      IconData(0xf17c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_MkI =
      IconData(0xf17d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_MkII =
      IconData(0xf17e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_MkIII =
      IconData(0xf17f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Mods =
      IconData(0xf180, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ModularItem =
      IconData(0xf181, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Natural =
      IconData(0xf182, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Noggles =
      IconData(0xf183, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Operator =
      IconData(0xf184, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_OrokinOn =
      IconData(0xf185, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_OwnedBlueprint =
      IconData(0xf186, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Oxides =
      IconData(0xf187, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Parazon =
      IconData(0xf188, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ParazonLong =
      IconData(0xf189, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ParazonLongShadow =
      IconData(0xf18a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ParazonLongShadow2 =
      IconData(0xf18b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Pheromones =
      IconData(0xf18c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Pilot =
      IconData(0xf18d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Pistol =
      IconData(0xf18e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PlayerShip =
      IconData(0xf18f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrexCategory =
      IconData(0xf190, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrimaryWeaponBow =
      IconData(0xf191, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrimaryWeaponLauncher =
      IconData(0xf192, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrimaryWeaponRifle =
      IconData(0xf193, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrimaryWeaponShotgun =
      IconData(0xf194, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrimaryWeaponSniper =
      IconData(0xf195, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrimaryWeaponSpeargun =
      IconData(0xf196, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrimaryWeaponSpecial =
      IconData(0xf197, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_PrimeParts =
      IconData(0xf198, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Prospector =
      IconData(0xf199, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Purchase =
      IconData(0xf19a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_QuestPickerActive =
      IconData(0xf19b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_QuestPickerCompleted =
      IconData(0xf19c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_QuestPickerMystery =
      IconData(0xf19d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Railjack =
      IconData(0xf19e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Railjack2 =
      IconData(0xf19f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RailjackAbilities =
      IconData(0xf1a0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RailjackCountermeasures =
      IconData(0xf1a1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RailjackOrdnance =
      IconData(0xf1a2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RailjackPilot =
      IconData(0xf1a3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RailjackTurrets =
      IconData(0xf1a4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RelatedItems =
      IconData(0xf1a5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Relic =
      IconData(0xf1a6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RelicAxi =
      IconData(0xf1a7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RelicLith =
      IconData(0xf1a8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RelicMeso =
      IconData(0xf1a9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RelicNeo =
      IconData(0xf1aa, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RequiemMod =
      IconData(0xf1ab, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RequiemRelic =
      IconData(0xf1ac, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RequirementsMet =
      IconData(0xf1ad, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ResearchCorpus =
      IconData(0xf1ae, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ResearchGrineer =
      IconData(0xf1af, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ResearchInfested =
      IconData(0xf1b0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ResearchOrokin =
      IconData(0xf1b1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ResearchRailjack =
      IconData(0xf1b2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ResearchTenno =
      IconData(0xf1b3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_ResourceDrone =
      IconData(0xf1b4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Rifle =
      IconData(0xf1b5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RifleOff =
      IconData(0xf1b6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RivenMod =
      IconData(0xf1b7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_RoundVial =
      IconData(0xf1b8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Salvage =
      IconData(0xf1b9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Sentinel =
      IconData(0xf1ba, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Shotgun =
      IconData(0xf1bb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Sigils =
      IconData(0xf1bc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Simaris =
      IconData(0xf1bd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Skins =
      IconData(0xf1be, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Solaris =
      IconData(0xf1bf, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_SquareVial =
      IconData(0xf1c0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Stance =
      IconData(0xf1c1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Strike =
      IconData(0xf1c2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Swatch =
      IconData(0xf1c3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Synthetics =
      IconData(0xf1c4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Synthetics2 =
      IconData(0xf1c5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Tactical =
      IconData(0xf1c6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Teleport =
      IconData(0xf1c7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Tenets =
      IconData(0xf1c8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Utility =
      IconData(0xf1c9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Utility2 =
      IconData(0xf1ca, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_VehiclesKdrive =
      IconData(0xf1cb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Warframe =
      IconData(0xf1cc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_WarframeOff =
      IconData(0xf1cd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Weapons =
      IconData(0xf1ce, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_Wild =
      IconData(0xf1cf, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_WoundedInfestedCritter =
      IconData(0xf1d0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData menu_WoundedInfestedPredator =
      IconData(0xf1d1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData nightmare =
      IconData(0xf1d2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData nightwave =
      IconData(0xf1d3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData nightwaves_daily =
      IconData(0xf1d4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData nightwaves_elite =
      IconData(0xf1d5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData nightwaves_weekly =
      IconData(0xf1d6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData ostron =
      IconData(0xf1d7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Arbiters_of_Hexis_ArbitersLevel1 =
      IconData(0xf1d8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Arbiters_of_Hexis_ArbitersLevel2 =
      IconData(0xf1d9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Arbiters_of_Hexis_ArbitersLevel3 =
      IconData(0xf1da, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Arbiters_of_Hexis_ArbitersLevel4 =
      IconData(0xf1db, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Arbiters_of_Hexis_ArbitersLevel5 =
      IconData(0xf1dc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Cephalon_Suda_CephalonSudaLevel1 =
      IconData(0xf1dd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Cephalon_Suda_CephalonSudaLevel2 =
      IconData(0xf1de, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Cephalon_Suda_CephalonSudaLevel3 =
      IconData(0xf1df, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Cephalon_Suda_CephalonSudaLevel4 =
      IconData(0xf1e0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Cephalon_Suda_CephalonSudaLevel5 =
      IconData(0xf1e1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Entrati_EntratiLevel1 =
      IconData(0xf1e2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Entrati_EntratiLevel2 =
      IconData(0xf1e3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Entrati_EntratiLevel3 =
      IconData(0xf1e4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Entrati_EntratiLevel4 =
      IconData(0xf1e5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Entrati_EntratiLevel5 =
      IconData(0xf1e6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Necraloid_NecraloidLevel1 =
      IconData(0xf1e7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Necraloid_NecraloidLevel2 =
      IconData(0xf1e8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Necraloid_NecraloidLevel3 =
      IconData(0xf1e9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_NegativeRank1 =
      IconData(0xf1ea, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_NegativeRank2 =
      IconData(0xf1eb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Neutral =
      IconData(0xf1ec, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_New_Loka_NewLokaLevel1 =
      IconData(0xf1ed, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_New_Loka_NewLokaLevel2 =
      IconData(0xf1ee, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_New_Loka_NewLokaLevel3 =
      IconData(0xf1ef, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_New_Loka_NewLokaLevel4 =
      IconData(0xf1f0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_New_Loka_NewLokaLevel5 =
      IconData(0xf1f1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Ostron_OstronLevel1 =
      IconData(0xf1f2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Ostron_OstronLevel2 =
      IconData(0xf1f3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Ostron_OstronLevel3 =
      IconData(0xf1f4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Ostron_OstronLevel4 =
      IconData(0xf1f5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Ostron_OstronLevel5 =
      IconData(0xf1f6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Red_Veil_RedVeilLevel1 =
      IconData(0xf1f7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Red_Veil_RedVeilLevel2 =
      IconData(0xf1f8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Red_Veil_RedVeilLevel3 =
      IconData(0xf1f9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Red_Veil_RedVeilLevel4 =
      IconData(0xf1fa, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Red_Veil_RedVeilLevel5 =
      IconData(0xf1fb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Solaris_United_SolarisLevel1 =
      IconData(0xf1fc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Solaris_United_SolarisLevel2 =
      IconData(0xf1fd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Solaris_United_SolarisLevel3 =
      IconData(0xf1fe, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Solaris_United_SolarisLevel4 =
      IconData(0xf1ff, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Solaris_United_SolarisLevel5 =
      IconData(0xf200, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Steel_Meridian_SteelMeridianLevel1 =
      IconData(0xf201, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Steel_Meridian_SteelMeridianLevel2 =
      IconData(0xf202, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Steel_Meridian_SteelMeridianLevel3 =
      IconData(0xf203, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Steel_Meridian_SteelMeridianLevel4 =
      IconData(0xf204, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Steel_Meridian_SteelMeridianLevel5 =
      IconData(0xf205, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Holdfasts_HoldfastsLevel1 =
      IconData(0xf206, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Holdfasts_HoldfastsLevel2 =
      IconData(0xf207, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Holdfasts_HoldfastsLevel3 =
      IconData(0xf208, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Holdfasts_HoldfastsLevel4 =
      IconData(0xf209, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Holdfasts_HoldfastsLevel5 =
      IconData(0xf20a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Perrin_Sequence_PerrinLevel1 =
      IconData(0xf20b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Perrin_Sequence_PerrinLevel2 =
      IconData(0xf20c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Perrin_Sequence_PerrinLevel3 =
      IconData(0xf20d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Perrin_Sequence_PerrinLevel4 =
      IconData(0xf20e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Perrin_Sequence_PerrinLevel5 =
      IconData(0xf20f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Quills_QuillsLevel1 =
      IconData(0xf210, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Quills_QuillsLevel2 =
      IconData(0xf211, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Quills_QuillsLevel3 =
      IconData(0xf212, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Quills_QuillsLevel4 =
      IconData(0xf213, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_The_Quills_QuillsLevel5 =
      IconData(0xf214, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_VentKids_VentKidsLevel1 =
      IconData(0xf215, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_VentKids_VentKidsLevel2 =
      IconData(0xf216, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_VentKids_VentKidsLevel3 =
      IconData(0xf217, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_VentKids_VentKidsLevel4 =
      IconData(0xf218, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_VentKids_VentKidsLevel5 =
      IconData(0xf219, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Vox_Solaris_VoxLevel1 =
      IconData(0xf21a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Vox_Solaris_VoxLevel2 =
      IconData(0xf21b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Vox_Solaris_VoxLevel3 =
      IconData(0xf21c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Vox_Solaris_VoxLevel4 =
      IconData(0xf21d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sigils_Vox_Solaris_VoxLevel5 =
      IconData(0xf21e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData simaris =
      IconData(0xf21f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData solaris =
      IconData(0xf220, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sp_logo =
      IconData(0xf221, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData standing =
      IconData(0xf222, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData wfcd =
      IconData(0xf223, fontFamily: _fontFamily, fontPackage: _fontPackage);
}
