/// Flutter icons NavisSysIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavisSysIcons
///      fonts:
///       - asset: fonts/NavisSysIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class NavisSysIcons {
  NavisSysIcons._();

  static const _kFontFam = 'NavisSysIcons';

  static const IconData archwing = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData nightmare = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData sortie = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData standing = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData voidfissure = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData wfcdLogoColor = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heat_wave = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData moon_solid = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData kuva = IconData(0xe80a, fontFamily: _kFontFam);
}
