# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Push the built release to Google Play beta track'
  lane :beta do
    begin
     `flutter pub global activate cider`

      tags = git_tags(limit: 2)
      analyze_commits(match: tags[1])
      
      changelog = conventional_changelog(format: 'plain', display_title: false, display_links: false, order: ['feat', 'fix', 'perf'])
      versionCode = ''

      Dir.chdir "../.." do
        version = "2.5.3+182"
        versionCode = version.split('+').last
      end

      File.open("metadata/android/en-US/changelogs/#{versionCode}.txt", 'w') {|f| f.write(changelog)}

      upload_to_play_store(
        track: 'beta',
        aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
        json_key: 'app/fastlane.json',
      )
    rescue => exception
      raise exception unless exception.message.include?('apkNotificationMessageKeyUpgradeVersionConflict')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end
end
