# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
setup_travis
update_fastlane

default_platform(:android)

platform :android do
  desc 'Push the built release to Google Play beta track'
  lane :beta do
    tag_name = ENV["TRAVIS_TAG"]
    directory = "#{ENV["TRAVIS_BUILD_DIR"]}/build/app/outputs/apk/release"

    analyze_commits(match: tag_name)

    begin
      upload_to_play_store(
        track: 'beta',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        json_key: 'app/fastlane.json',
        skip_upload_screenshots: true,
        skip_upload_images: true
      )

      set_github_release(
        repository_name: 'WFCD/navis',
        api_token: ENV["GIT_TOKEN"],
        name: tag_name,
        tag_name: tag_name,
        description: "#{conventional_changelog}",
        commitish: 'stable',
        upload_assets: ["#{directory}/app-arm64-v8a-release.apk", "#{directory}/app-armeabi-v7a-release.apk", "#{directory}/app-x86_64-release.apk"]
      )
    rescue => exception
      raise exception unless exception.message.include?('apkNotificationMessageKeyUpgradeVersionConflict')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end
end
