# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
setuo_travis
update_fastlane

default_platform(:android)

# This should be run after running
# flutter build apk --release
# to build the app using the Flutter toolchain.
platform :android do
  desc 'Push the built release to Google Play beta track'
  lane :beta do
    begin
      upload_to_play_store(
        track: 'beta',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        json_key: 'app/fastlane.json',
        skip_upload_screenshots: true,
        skip_upload_images: true
      )
    rescue => exception
      raise exception unless exception.message.include?('apkNotificationMessageKeyUpgradeVersionConflict')
      puts 'Current version already present on the Play Store. Omitting this upload.'
    end
  end
end
