name: inventoria
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  flutter:
    sdk: flutter
  http: ^1.4.0
  http_client:
    path: ../http_client
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  path_provider: ^2.1.5
  warframestat_client: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0
  mocktail: ^1.0.4
