name: Dev builds

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  MATOMO_URL: ${{ secrets.MATOMO_URL }}

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Decode signing key and services json
        env:
          TENNO_CIPHER: ${{ secrets.TENNO_CIPHER }}
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
          KEYSTORE: ${{ secrets.KEYSTORE }}
        run: |
          echo $KEYSTORE | base64 --decode > android/keystore.jks
          echo $FIREBASE_OPTIONS | base64 --decode > lib/firebase_options.dart

      - name: Build apks
        run: flutter build apk --dart-define=SENTRY_DSN=$SENTRY_DSN --dart-define=MATOMO_URL=$MATOMO_URL --flavor dev -t lib/main_dev.dart --split-per-abi

      - uses: actions/upload-artifact@v3
        with:
          name: android-test-artifacts
          path: "build/app/outputs/flutter-apk/app-*-dev-release.apk"

  ios:
    runs-on: macos-latest

    env:
      FIREBASE_IOS: ${{ secrets.FIREBASE_IOS }}

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Decode signing key and services json
        env:
          FIREBASE_IOS: ${{ secrets.FIREBASE_IOS }}
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS }}
        run: |
          echo $FIREBASE_IOS | base64 --decode > ios/firebase_app_id_file.json
          echo $FIREBASE_OPTIONS | base64 --decode > lib/firebase_options.dart

      - name: Pod update
        run: pod repo update

      - name: Build ios using flutter
        run: flutter build ios --dart-define=SENTRY_DSN=$SENTRY_DSN --dart-define=MATOMO_URL=$MATOMO_URL -t lib/main_dev.dart --no-codesign

      - uses: actions/upload-artifact@v3
        with:
          name: ios-test-artifacts
          path: "build/ios/iphoneos/Runner.app"
