name: market_repo

on:
  pull_request:
    paths:
      - "packages/market_repository/**"
      - ".github/workflows/market_repo.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/market_repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install Dependencies
        run: pub get

      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed lib test

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        run: dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: packages/market_repository/coverage/lcov.info
          min_coverage: 90
          exclude: "**/*.g.dart **/*.gen.dart"
