name: market_repo

on:
  pull_request:
    paths:
      - "packages/market_repository/**"
      - ".github/workflows/market_repo.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/market_repository
      min_coverage: 90
