name: Testing
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Install app dependencies
        run: flutter pub get

      - name: Unit Test app
        run: flutter test --coverage

      - name: Uploade coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
