name: Testing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - master
      - beta

  pull_request:
    branches:
      - master
      - beta

jobs:
  test:
    secrets: inherit
    uses: ./.github/workflows/build_test.yml
  release:
    if: github.event_name != 'pull_request'
    needs: [test]
    secrets: inherit
    uses: ./.github/workflows/release.yml