name: user_settings

on:
  pull_request:
    paths:
      - "packages/user_settings/**"
      - ".github/workflows/user_settings.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/user_settings
      min_coverage: 5
