name: worldstate_repo

on:
  pull_request:
    paths:
      - "packages/worldstate_repository/**"
      - ".github/workflows/worldstate_repo.yaml"

jobs:
  test:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/worldstate_repository
      min_coverage: 50
