// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:cache_client/src/hive/hive_adapters.dart';
import 'package:hive_ce/hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CachedItemAdapter());
  }
}
